ALTER PROCEDURE INSERTLOANPROC
(
	@Dealer_ID int,
	@CarYear int,
	@Make varchar(50),
	@Model varchar(50),
	@VIN varchar(17),
	@Loan_Amount Money
)
AS

--CHECK IF LOAN IS ACCEPTED
BEGIN
	declare @APR_RATE float;
	DECLARE @DEALER_SCORE INT;
	DECLARE @ACCEPTED BIT;
	SELECT @DEALER_SCORE = DEALER_SCORE FROM DEALER WHERE DEALER_ID = @DEALER_ID;
	IF @DEALER_SCORE > 200
		SET @ACCEPTED = 1
	ELSE 
		SET @ACCEPTED = 0
END

IF (@ACCEPTED = 1)
BEGIN
	DECLARE @Vehicle_id int;
	
	--INSERT VEHICLE IN VEHICLE TABLE
	INSERT INTO VEHICLE([YEAR],MAKE,MODEL,VIN)
		VALUES(@CarYear, @Make, @Model, @VIN)
	
	--GET VEHICLE ID	
	SELECT @Vehicle_id = vehicle_ID from VEHICLE where vin = @vin
	
	SET @APR_RATE = (@DEALER_SCORE/100)
	
	--INSERT LOAN INTO LOAN TABLE
	INSERT INTO LOAN(VEHICLE_ID, DEALER_ID, LOAN_AMOUNT , APR_RATE)
		VALUES(@Vehicle_id,@DEALER_ID,@LOAN_AMOUNT, @APR_RATE)
	
	EXEC INSERTDEALERSCORE @DEALER_ID = @DEALER_ID;
	
	
END		

IF @ACCEPTED = 0
BEGIN
	SET @APR_RATE = 0;
END	

BEGIN
	 SELECT @ACCEPTED as "ACCEPTED", @APR_RATE as "APR_RATE"
END




