CREATE PROCEDURE INSERTDEALERSCORE
(
	@Dealer_ID int
)
AS
BEGIN
	UPDATE DEALER
		SET DEALER_SCORE = 
	 (SELECT
	(AVG_Score/Max_Score)*(1000) as "Score"
	FROM
		(SELECT 
		Max(([YEAR])/(APR_RATE*Loan_Amount)) as "Max_Score",
		AVG((([YEAR])/(APR_RATE*Loan_Amount))) as "AVG_Score"
		FROM LOAN L
		JOIN VEHICLE V
		ON L.VEHICLE_ID = V.VEHICLE_ID 
		WHERE L.DEALER_ID = @DEALER_ID) as tbl)
		WHERE DEALER_ID = @DEALER_ID
END		
BEGIN
		SELECT DEALER_SCORE
		FROM DEALER 
		WHERE DEALER_ID = @DEALER_ID
END





	
	
